import os
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.units import inch, mm
from reportlab.lib import colors
from reportlab.platypus.tables import Table, TableStyle
from reportlab.lib.pagesizes import A4 # Import A4

# --- Configuration (can be shared or passed) ---
# Page Dimensions
PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN_LEFT = MARGIN_RIGHT = 15 * mm
MARGIN_TOP = MARGIN_BOTTOM = 15 * mm
FRAME_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
FRAME_HEIGHT = PAGE_HEIGHT - MARGIN_TOP - MARGIN_BOTTOM

# Styles for ReportLab
styles = getSampleStyleSheet()
styleN = styles['Normal']
styleH = styles['h1']
styleH2 = styles['h2']
styleH3 = styles['h3']
styleL = styles['Bullet']

def _header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('Helvetica-Bold', 10)
    canvas.drawString(MARGIN_LEFT, PAGE_HEIGHT - MARGIN_TOP + 5*mm, "Charger Performance Report")
    canvas.setFont('Helvetica', 9)
    canvas.drawRightString(PAGE_WIDTH - MARGIN_RIGHT, PAGE_HEIGHT - MARGIN_TOP + 5*mm, f"Date: {getattr(doc, 'report_date', 'N/A')}")
    canvas.setFont('Helvetica', 9)
    canvas.drawCentredString(PAGE_WIDTH / 2.0, MARGIN_BOTTOM - 5*mm, f"Page {doc.page}")
    canvas.restoreState()

def create_title_page(story, report_date):
    story.append(Paragraph("<font size=24>Charger Performance Report</font>", styles['h1']))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(f"<font size=18>For the period: {report_date}</font>", styles['h2']))
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("<font size=12>Generated by Safivolt Analytics</font>", styles['Normal']))
    story.append(PageBreak())

def create_chapter_title(title_text, level=1):
    if level == 1:
        return Paragraph(f"<font size=16>{title_text}</font>", styles['h2'])
    elif level == 2:
        return Paragraph(f"<font size=14>{title_text}</font>", styles['h3'])
    else:
        return Paragraph(f"<font size=12>{title_text}</font>", styles['h4'])

def create_chapter_body(content_text):
    return Paragraph(content_text, styles['Normal'])

def create_table_flowable(df, col_widths=None):
    if df.empty:
        return Paragraph("No data available for this table.", styleN)

    data = [df.columns.tolist()] + df.values.tolist()
    
    table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ADD8E6')), # Light Blue header
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ])
    
    table = Table(data, colWidths=col_widths)
    table.setStyle(table_style)
    return table

def generate_pdf_report(output_filename, report_data, chart_paths):
    """
    Generates the PDF report using ReportLab.
    report_data is a dictionary containing processed data and metrics.
    chart_paths is a dictionary of paths to generated chart images.
    """
    story = []
    doc = SimpleDocTemplate(output_filename,
                            pagesize=A4,
                            leftMargin=MARGIN_LEFT,
                            rightMargin=MARGIN_RIGHT,
                            topMargin=MARGIN_TOP,
                            bottomMargin=MARGIN_BOTTOM)

    doc.report_date = report_data['report_date_range']

    # Add Title Page
    create_title_page(story, report_data['report_date_range'])

    # --- Executive Summary ---
    story.append(create_chapter_title("1. Executive Summary", level=1))
    story.append(Spacer(1, 0.2 * inch))

    exec_metrics = report_data['executive_summary_metrics']
    executive_summary_text = f"""
    This report provides an overview of charger performance for the period from {report_data['start_date']} to {report_data['end_date']}.
    A total of <b>{exec_metrics['total_chargers']}</b> unique chargers were analyzed.
    Across these chargers, a total of <b>{exec_metrics['total_sessions']}</b> charging sessions were recorded, delivering approximately <b>{exec_metrics['total_energy_delivered']:.2f} kWh</b> of energy.
    Key insights and anomalies will be detailed in the following sections.
    """
    story.append(create_chapter_body(executive_summary_text))
    story.append(Spacer(1, 0.2 * inch))
    story.append(PageBreak()) 

    # --- Charger Performance Overview ---
    story.append(create_chapter_title("2. Charger Performance Overview", level=1))
    story.append(Spacer(1, 0.2 * inch))

    charger_performance = report_data['charger_performance_metrics']

    story.append(create_chapter_body(
        "This section highlights the performance of individual chargers, "
        "including their total sessions, energy delivered, and average uptime."
    ))
    story.append(Spacer(1, 0.2 * inch))

    story.append(create_chapter_title("Charger Performance Table", level=2))
    story.append(create_table_flowable(charger_performance.reset_index()))
    story.append(PageBreak())

    if 'charger_energy_chart' in chart_paths and os.path.exists(chart_paths['charger_energy_chart']):
        story.append(create_chapter_title("Energy Delivered per Charger", level=2))
        story.append(Image(chart_paths['charger_energy_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 2: Total energy delivered by each charger."))
        story.append(Spacer(1, 0.2 * inch))

    if 'charger_sessions_chart' in chart_paths and os.path.exists(chart_paths['charger_sessions_chart']):
        story.append(create_chapter_title("Sessions per Charger", level=2))
        story.append(Image(chart_paths['charger_sessions_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 3: Total charging sessions per charger."))
        story.append(PageBreak())

    # --- Usage Patterns (Time-Based Analysis) ---
    story.append(create_chapter_title("3. Usage Patterns (Time-Based Analysis)", level=1))
    story.append(Spacer(1, 0.2 * inch))

    if 'usage_over_time_chart' in chart_paths and os.path.exists(chart_paths['usage_over_time_chart']):
        story.append(create_chapter_title("Sessions per Hour", level=2))
        story.append(create_chapter_body(
            "This chart illustrates the distribution of charging sessions throughout the day, "
            "helping to identify peak and off-peak usage periods."
        ))
        story.append(Image(chart_paths['usage_over_time_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 4: Number of charging sessions per hour."))
        story.append(PageBreak())
    else:
        story.append(create_chapter_body("No valid timestamp data found for usage pattern analysis or chart could not be generated."))
    story.append(PageBreak()) # Page break at the end of section

    # --- Charging Behavior Analysis ---
    story.append(create_chapter_title("4. Charging Behavior Analysis", level=1))
    story.append(Spacer(1, 0.2 * inch))
    
    behavior_metrics = report_data['charging_behavior_metrics']
    
    story.append(create_chapter_body(
        f"The average session duration across all chargers was <b>{behavior_metrics['average_session_duration']:.2f} minutes</b>. "
        "Further details on session duration distribution and fast vs slow charging usage are provided below."
    ))
    story.append(Spacer(1, 0.2 * inch))

    if 'session_duration_histogram' in chart_paths and os.path.exists(chart_paths['session_duration_histogram']):
        story.append(create_chapter_title("Session Duration Distribution", level=2))
        story.append(Image(chart_paths['session_duration_histogram'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 5: Distribution of charging session durations."))
        story.append(Spacer(1, 0.2 * inch))

    if 'fast_slow_pie_chart' in chart_paths and os.path.exists(chart_paths['fast_slow_pie_chart']):
        story.append(create_chapter_title("Fast vs Slow Charging Usage", level=2))
        story.append(Image(chart_paths['fast_slow_pie_chart'], width=3 * inch, height=3 * inch)) # Smaller size for pie chart
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 6: Proportion of fast versus slow charging sessions."))
    else:
        story.append(create_chapter_body("Charging type data not available or charts could not be generated."))
    story.append(PageBreak()) # This page break is now sufficient for the end of Section 4

    # --- Power & Technical Metrics ---
    story.append(create_chapter_title("5. Power & Technical Metrics", level=1))
    story.append(Spacer(1, 0.2 * inch))

    tech_metrics = report_data['power_technical_metrics']

    story.append(create_chapter_body(
        "This section provides insights into the power and technical performance of the chargers, "
        "including temperature readings, voltage/current trends, and charging rate trends."
    ))
    story.append(Spacer(1, 0.2 * inch))

    if tech_metrics['average_temperature'] > 0:
        story.append(create_chapter_body(f"The average charger temperature recorded was <b>{tech_metrics['average_temperature']:.2f} °C</b>."))
        story.append(Spacer(1, 0.1 * inch))
    if 'temperature_over_time_chart' in chart_paths and os.path.exists(chart_paths['temperature_over_time_chart']):
        story.append(create_chapter_title("Temperature Over Time", level=2))
        story.append(Image(chart_paths['temperature_over_time_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 7: Charger temperature trends over time."))
        story.append(Spacer(1, 0.2 * inch))

    if tech_metrics['average_voltage'] > 0 or tech_metrics['average_current'] > 0:
        story.append(create_chapter_body(f"Average voltage: <b>{tech_metrics['average_voltage']:.2f} V</b>, Average current: <b>{tech_metrics['average_current']:.2f} A</b>."))
        story.append(Spacer(1, 0.1 * inch))
    if 'voltage_current_chart' in chart_paths and os.path.exists(chart_paths['voltage_current_chart']):
        story.append(create_chapter_title("Voltage Over Time", level=2))
        story.append(Image(chart_paths['voltage_current_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 8: Voltage trends over time."))
        story.append(Spacer(1, 0.2 * inch))
    if 'current_chart' in chart_paths and os.path.exists(chart_paths['current_chart']):
        story.append(create_chapter_title("Current Over Time", level=2))
        story.append(Image(chart_paths['current_chart'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 9: Current trends over time."))
        story.append(Spacer(1, 0.2 * inch))

    if tech_metrics['average_charging_rate'] > 0:
        story.append(create_chapter_body(f"The average charging rate observed was <b>{tech_metrics['average_charging_rate']:.2f} kW</b>."))
        story.append(Spacer(1, 0.1 * inch))
    if 'charging_rate_scatter' in chart_paths and os.path.exists(chart_paths['charging_rate_scatter']):
        story.append(create_chapter_title("Charging Rate Trends", level=2))
        story.append(Image(chart_paths['charging_rate_scatter'], width=5 * inch, height=3 * inch))
        story.append(Spacer(1, 0.1 * inch))
        story.append(create_chapter_body("Figure 10: Charging rate trends over time."))
        story.append(PageBreak())
    else:
        story.append(create_chapter_body("No technical metrics data available or charts could not be generated."))
    story.append(PageBreak()) # Page break at the end of section

    # --- Issues & Anomalies ---
    story.append(create_chapter_title("6. Issues & Anomalies", level=1))
    story.append(Spacer(1, 0.2 * inch))

    anomalies = report_data.get('anomalies', {})
    if any(anomalies.values()): # Check if any anomaly list is non-empty
        if anomalies.get('high_temp_chargers'):
            story.append(create_chapter_title("High Temperature Chargers", level=2))
            story.append(create_chapter_body(
                f"The following chargers exceeded the high temperature threshold ({report_data.get('TEMP_THRESHOLD_HIGH', 'N/A')} °C): " +
                ", ".join(anomalies['high_temp_chargers'])
            ))
            story.append(Spacer(1, 0.1 * inch))

        if anomalies.get('low_uptime_chargers'):
            story.append(create_chapter_title("Low Uptime Chargers", level=2))
            story.append(create_chapter_body(
                f"The following chargers reported uptime below the threshold ({report_data.get('UPTIME_THRESHOLD_LOW', 'N/A')}%): " +
                ", ".join(anomalies['low_uptime_chargers'])
            ))
            story.append(Spacer(1, 0.1 * inch))

        if anomalies.get('low_charge_rate_chargers'):
            story.append(create_chapter_title("Low Charging Rate Chargers", level=2))
            story.append(create_chapter_body(
                f"The following chargers had an average charging rate below the threshold ({report_data.get('CHARGE_RATE_THRESHOLD_LOW', 'N/A')} kW), indicating potential underutilization or issues: " +
                ", ".join(anomalies['low_charge_rate_chargers'])
            ))
            story.append(Spacer(1, 0.1 * inch))
    else:
        story.append(create_chapter_body("No significant anomalies detected during this period."))
    story.append(PageBreak())
    
    # --- Charger Performance Rankings ---
    story.append(create_chapter_title("7. Charger Performance Rankings", level=1))
    story.append(Spacer(1, 0.2 * inch))

    rankings = report_data.get('rankings', {})
    if rankings.get('top_kwh_chargers') or rankings.get('bottom_uptime_chargers'):
        if rankings.get('top_kwh_chargers'):
            story.append(create_chapter_title("Top Chargers by Energy Delivered (kWh)", level=2))
            top_kwh_data = [['Serial Number', 'Total Energy (kWh)']] + rankings['top_kwh_chargers']
            story.append(Table(top_kwh_data, style=TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ADD8E6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ])))
            story.append(Spacer(1, 0.1 * inch))

        if rankings.get('bottom_uptime_chargers'):
            story.append(create_chapter_title("Chargers with Lowest Uptime (%)", level=2))
            bottom_uptime_data = [['Serial Number', 'Average Uptime (%)']] + rankings['bottom_uptime_chargers']
            story.append(Table(bottom_uptime_data, style=TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ADD8E6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ])))
            story.append(Spacer(1, 0.1 * inch))
    else:
        story.append(create_chapter_body("No charger rankings available for this period."))
    story.append(PageBreak())

    # --- Charger Health Scores ---
    story.append(create_chapter_title("8. Charger Health Scores", level=1))
    story.append(Spacer(1, 0.2 * inch))

    health_scores_df = report_data.get('health_scores')
    if health_scores_df is not None and not health_scores_df.empty:
        story.append(create_table_flowable(health_scores_df))
    else:
        story.append(create_chapter_body("No health scores available for chargers."))
    story.append(PageBreak())

    # --- Key Insights & Recommendations ---
    story.append(create_chapter_title("9. Key Insights & Recommendations", level=1))
    story.append(Spacer(1, 0.2 * inch))

    insights = report_data.get('insights', [])
    recommendations = report_data.get('recommendations', [])

    if insights:
        story.append(create_chapter_title("Key Insights", level=2))
        story.append(ListFlowable([ListItem(Paragraph(i, styleN)) for i in insights], bulletType='bullet', start='circle'))
        story.append(Spacer(1, 0.2 * inch))

    if recommendations:
        story.append(create_chapter_title("Recommendations", level=2))
        story.append(ListFlowable([ListItem(Paragraph(r, styleN)) for r in recommendations], bulletType='bullet', start='circle'))
        story.append(Spacer(1, 0.2 * inch))

    if not insights and not recommendations:
        story.append(create_chapter_body("No specific insights or recommendations generated for this period."))
    
    story.append(PageBreak())

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
